version = 1

exclude_patterns = [
    "dist/**",
    "build/**",
    "node_modules/**",
    "coverage/**",
    "tmp/**"
]

test_patterns = [
    "src/**/*.test.ts",
    "src/**/*.test.tsx",
    "src/services/tests/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
      "nodejs",
      "browser"
  ]
  plugins = ["react"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true
