repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.3.0
    hooks:
      - id: detect-secrets
  - repo: local
    hooks:
      - id: test
        name: Run tests and check coverage
        entry: npm test -- --coverage
        language: system
        pass_filenames: false
