sonar.projectKey=heitorpolidoro_meridian
sonar.organization=heitorpolidoro
sonar.sources=src,server.ts
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,dist/**,coverage/**,src/main.tsx,src/App.tsx
sonar.coverage.exclusions=src/main.tsx,src/App.tsx
