name: Standard Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    uses: heitorpolidoro/.github/.github/workflows/node-standard-ci.yml@master
    with:
      node-versions: "['22.x', '24.x']"
      sonar-node-version: "24.x"
      enable-deepsource: true
    secrets: inherit # pragma: allowlist secret
